### PR TITLE
 Fix TypeError when formatting numbers <= 1e-7

### PR DESCRIPTION
**Pull request by tsullivan**
Fixes https://github.com/elastic/numeral-js/issues/6

```
> var numeral = require('./numeral');
undefined
> numeral('0.0000001').format('0,0.00');
'1e-7'
```

### CODE REVIEW

**Review by spalger — APPROVED** [review]
LGTM

**Review by w33ble — APPROVED** [review]

**Comment by tsullivan** [comment]
Alright, what is the right way to publish this patch? 

- Looks like I need to use `npm publish` since I have 2FA and that doesn't work with `yarn publish`: https://github.com/yarnpkg/yarn/issues/4904
- Using `npm publish` automatically tries to add the `package-lock.json` to git, so I had to undo my `.gitignore` change
- `npm publish` is complaining `404  '@elastic/numeral' is not in the npm registry.`

???

**Comment by w33ble** [comment]
On 3/30...
> @elastic/numeral 2.3.2 published :tada:

**Pull request merged**
